##########################################################################################
#                                                                                        #
#                                                                                        #
#				          Simple Tokens By Teyir > Teyir.fr                              #
#                                                                                        #
#                       For support → http://discord.teyir.fr                            #
#                                                                                        #
#                                                                                        #
##########################################################################################

# For the minecraft color codes > https://www.spigotmc.org/attachments/example2-png.188806/

database:
  #
  # Available settings: MySQL
  #
  # MySQL → Remote storage support multiples server
  #
  MySQL:
    user: root
    pass:
    host: localhost
    port: 3306
    db: minecraft

general:
  language: EN  #Language is the language file name (ex: EN for the EN.yml file in the lang folder)
  startBalance: 30
  tokenName: 'Tokens'
  prefix: '&bTokens &8» &7'
  topMaxDisplay: 10
  displayFramedOnCommandQuery: true #Display the header and footer when the command is executed ?

transactionLogs:
  console: true
  file: true